# -*- coding: utf-8 -*-
# main_exe/langs/en.py

ENGLISH_DICT = {
    # ── Main Interface ────────────────────────────────────────
    'main_title':          (1001, 'FDSB'),
    'no_bots_hint':        (1002, 'No bots found. Click "New Bot" to create one.'),
    'new_bot':             (1003, 'New Bot'),
    'discord':             (1004, 'Discord'),
    'github':              (1005, 'GitHub'),

    # ── Create Bot Window ─────────────────────────────────────
    'name_label':          (1006, 'Name'),
    'token_label':         (1007, 'Token'),
    'name_hint':           (1008, 'Enter bot name'),
    'token_hint':          (1009, 'Enter bot token'),
    'make':                (1010, 'Create'),
    'image_label':         (1011, 'Image'),
    'ok':                  (1012, 'OK'),
    'token_required':      (1013, 'Token is required'),
    'name_taken':          (1014, 'Name already taken\nChoose a different name'),

    # ── Bot Dashboard ─────────────────────────────────────────
    'state_server':        (1015, 'Server Status'),
    'online':              (1016, 'Online'),
    'offline':             (1017, 'Offline'),
    'start':               (1018, 'Start'),
    'stop':                (1019, 'Stop'),
    'whats_new':           (1020, 'What\'s New'),
    'no_updates':          (1021, 'No updates available.'),
    'no_file':             (1022, 'Updates file not found.'),
    'read_error':          (1023, 'Unable to read file.'),
    'invite_bot':          (1024, 'Invite Bot'),
    'back':                (1025, 'Back'),
    'main_tab':            (1026, 'Main'),
    'commands_tab':        (1027, 'Commands'),
    'variables':           (1028, 'Variables'),
    'settings':            (1029, 'Settings'),
    'avatar_none':         (1030, 'No Avatar'),
    'tab_main':            (1117, 'Main'),
    'tab_commands':        (1118, 'Commands'),
    'tab_variables':       (1119, 'Variables'),
    'tab_settings':        (1120, 'Settings'),

    # ── Settings ──────────────────────────────────────────────
    'general_section':     (1031, 'General'),
    'design_section':      (1032, 'Design'),
    'info_section':        (1033, 'Information'),
    'name_project':        (1034, 'Project Name'),
    'token_field':         (1035, 'Bot Token'),
    'bot_name_hint':       (1036, 'Bot Name'),
    'bot_token_hint':      (1037, 'Bot Token'),
    'save':                (1038, 'Save'),
    'language':            (1039, 'Language'),
    'wiki':                (1040, 'Wiki'),
    'link':                (1041, '(Link)'),
    'restart_notice':      (1042, 'Restarting...'),

    # ── Export Data ───────────────────────────────────────────
    'export_section':      (1043, 'Export Data'),
    'export_desc':         (1044, 'Export commands and variables as a ZIP file'),
    'export_zip':          (1045, 'Export ZIP'),
    'no_bot_selected':     (1046, 'No bot selected!'),
    'folders_not_found':   (1047, 'Folders not found!'),
    'export_failed':       (1048, 'Export failed!'),

    # ── Danger Zone / Delete ──────────────────────────────────
    'danger_zone':         (1049, 'Danger Zone'),
    'delete_bot_perm':     (1050, 'Delete this bot permanently'),
    'captcha_enter':       (1051, 'Enter 3 digits'),
    'captcha_hint':        (1052, 'Enter the 3 digits shown above'),
    'confirm_delete':      (1053, 'Confirm Deletion'),
    'captcha_wrong':       (1054, 'Wrong code — Try again'),

    # ── Themes Names ──────────────────────────────────────────
    'system_wh':           (1055, 'System (Light)'),
    'system_da':           (1056, 'System (Dark)'),
    'blue_sky':            (1057, 'Blue - Sky'),
    'yellow_bile':         (1058, 'Yellow - Gold'),
    'v2_dark':             (1059, 'Dark Gold'),

    # ── commands_view ─────────────────────────────────────────
    'commands_slash':      (1060, '/ Commands'),
    'info_command':        (1061, 'Command Info'),
    'command_editor':      (1062, 'Command Editor'),
    'total_lines':         (1063, 'Lines'),
    'total_text':          (1064, 'Characters'),
    'fdscript_hint':       (1065, '# FDScript code here...'),
    'prefix_label':        (1066, 'Prefix'),
    'prefix_hint':         (1067, 'Example: !cmd'),
    'search':              (1068, 'Search'),
    'commands':            (1069, 'Commands'),
    'no_cmds_hint':        (1070, 'No commands found. Click + to create one.'),
    'del':                 (1071, 'Delete'),
    'name_required':       (1072, 'Name is required'),
    'delete_q':            (1073, 'Delete?'),
    'delete_confirm':      (1074, 'Are you sure you want to delete "{item_name}"?\nThis action cannot be undone.'),
    'dest_event':          (1075, 'Event'),
    'dest_cmd':            (1076, 'Command'),
    'commands_label':      (1077, 'Enter command name'),
    'unsaved_title':       (1113, 'Unsaved Changes'),
    'unsaved_body':        (1114, 'There are unsaved changes. Do you want to save them before exiting?'),
    'discard':             (1115, 'Discard'),

    # ── wiki_view ─────────────────────────────────────────────
    'tab_wiki':             (1121, 'Wiki'),
    'search_hint':          (1122, 'Search a function...'),
    'check_updates':        (1123, 'Check for updates'),
    'checking':             (1124, 'Checking...'),
    'downloading':          (1125, 'Downloading wiki...'),
    'up_to_date':           (1126, 'Wiki is up to date (v{v})'),
    'update_available':     (1127, 'New update available (v{v})'),
    'update_failed':        (1128, 'Failed to check for updates'),
    'no_cache':             (1129, 'No local data yet. Press "Check for updates".'),
    'no_results':           (1130, 'No results'),
    'function_info':        (1131, 'Function info'),
    'no_details':           (1132, 'No details available'),
    'open_dashboard':       (1133, 'Open dashboard'),
    'copy_syntax':          (1134, 'Copy'),
    'copied':               (1135, 'Copied!'),
    'syntax':               (1136, 'Syntax'),
    'parameters':           (1137, 'Parameters'),
    'example':              (1138, 'Example'),
    'notes':                (1139, 'Notes'),
    'warnings':             (1140, 'Warnings'),
    'required':             (1141, 'Required'),
    'optional':             (1142, 'Optional'),
    'not_used_in_bot':      (1143, "This function is not used in this bot's commands"),

    # ── Old Keys ──────────────────────────────────────────────
    'create_file':         (1116, 'Create New File'),
    'bot_token':           (1078, 'Bot Token'),
    'start_server':        (1079, 'Start Server'),
    'stop_server':         (1080, 'Stop Server'),
    'files_list':          (1081, 'Files List'),
    'run':                 (1082, 'Run'),
    'file_name':           (1083, 'File Name'),
    'file_content':        (1084, 'File Content'),
    'variable_name':       (1085, 'Variable Name'),
    'variable_value':      (1086, 'Variable Value'),
    'add_variable':        (1087, 'Add Variable'),
    'no_files':            (1088, 'No files'),
    'no_variables':        (1089, 'No variables'),
    'enter_token':         (1090, 'Enter bot token'),
    'server_status':       (1091, 'Server Status'),
    'running':             (1092, 'Running'),
    'stopped':             (1093, 'Stopped'),
    'edit':                (1094, 'Edit'),
    'delete':              (1095, 'Delete'),
    'new_file':            (1096, 'New File'),
    'arabic':              (1097, 'Arabic'),
    'english':             (1098, 'English'),
    'confirm':             (1099, 'Confirm'),
    'cancel':              (1100, 'Cancel'),
    'success':             (1101, 'Success'),
    'error':               (1102, 'Error'),
    'file_saved':          (1103, 'File saved'),
    'variable_added':      (1104, 'Variable added'),
    'enter_file_name':     (1105, 'Enter file name'),
    'enter_variable_name': (1106, 'Enter variable name'),
    'file_prefix':         (1107, 'File Prefix'),
    'enter_prefix':        (1108, 'Enter prefix'),
    'prefix':              (1109, 'Prefix'),
    'edit_prefix':         (1110, 'Edit Prefix'),
    'prefix_updated':      (1111, 'Prefix updated'),
    'toggle_language':     (1112, 'English'), 

    # ── wiki_view filters ───────────────────────────────────
    'filter_all':           (1148, 'All'),
    'filter_command':       (1149, 'Command'),
    'filter_event':         (1150, 'Event'),

    # ── wiki_view callouts ───────────────────────────────────
    'callout_note':         (1144, 'Note'),
    'callout_limit':        (1145, 'Limit'),
    'callout_important':    (1146, "It's important!"),
    'callout_question':     (1147, 'What is this?'),

    # ── variables_view ────────────────────────────────────────
    'variables_slash':      (1151, "Variable's /"),
    'scoped_vars':          (1152, 'Per-user values'),
    'value_label':          (1153, 'Value'),
    'var_name_hint':        (1154, 'variable_name'),
    'var_value_hint':       (1155, 'variable_value'),
    'info_var':             (1156, 'Variable Info'),
    'invalid_json':         (1157, 'Invalid JSON'),
    'json_must_be_object':  (1158, 'Top level value must be a JSON object ({"userID": "value"}).'),

    # ── App Updater ───────────────────────────────────────────
    'app_update_title':           (1159, 'Update Available'),
    'app_update_new_version':     (1160, 'New Version'),
    'app_update_current_version': (1161, 'Current'),
    'app_update_no_changelog':    (1162, 'No changelog available for this update.'),
    'app_update_later':           (1163, 'Later'),
    'app_update_now':             (1164, 'Update Now'),
    'app_update_downloading':     (1165, 'Downloading'),
    'app_update_done':            (1166, 'Download complete ✓'),
    'app_update_failed':          (1167, 'Download failed'),
    'app_update_open_installer':  (1168, 'Open Installer'),
    'app_update_installer_opened':(1169, 'Installer opened. Finish installing, then reopen the app.'),
    'app_update_open_failed':     (1170, 'Could not open the installer file'),

    # ── wiki_view filters (extended) ─────────────────────────
    'filter_variable':      (1171, 'Variables'),
    'filter_discord':       (1172, 'Discord'),
    'filter_time':          (1173, 'Time'),
    'filter_other':         (1174, 'Other'),
}